config/routes.rb
Recordz::Application.routes.draw do
  root 'records#index'

  resources :users
  resources :records
  resources :bands
  resources :artists
  resource :session, only: [:new, :create, :delete]
  resources :artists do
  	put 'add_bands', on: :member
	put 'add_records', on: :member
  end
  resources :bands do
	put 'add_artists', on: :member
	put 'add_records', on: :member
  end
  resources :records do
	put 'add_bands', on: :member
	put 'add_artists', on: :member
	put 'add_to_collection', on: :member
	put 'remove_from_collection', on: :member
  end

  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	include AddRecords

	has_and_belongs_to_many :bands
	has_and_belongs_to_many :records

	validates :name, presence: true

	

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :add_bands, :add_records]
  before_action :check_signed_in, except: [:index, :show]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
	@bands = Band.all
	@records = Record.all
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)
    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end
 def add_bands
	band = Band.find(params[:band_id])
	if @artist.add_band(band)
	  redirect_to artist_path(@artist), notice: 'Band was successfully added.'
	else 
	 redirect_to artist_path(@artist), notice: 'Failed to add band. Already added?'
	end
 end
  def add_records
	perf = Record.find(params[:record_id])
	if @artist.add_record(perf)
	  redirect_to artist_path(@artist), notice: 'Record was successfully added.'
	else 
	 redirect_to artist_path(@artist), notice: 'Failed to add record. Already added?'
	end
 end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :info)
    end	

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<h2>Artists</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%=link_to artist.name, artist_path(artist) %></td>
        <td><%= artist.info %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%if current_user %>
<%= link_to 'New Artist', new_artist_path, class:"btn btn-primary" %>
<%end%>
</p>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

app/views/artists/show.html.erb
<h1>
  <%= @artist.name %>
</h1>

<p>
  <%= @artist.info %>
</p>
<br>
<p>

<% if not @artist.bands.empty? %>
<h3>Member of <%= pluralize(@artist.bands.count, 'band')%>:</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
	<% @artist.bands.each do |r| %>
    	<tr>
	      <td><%= link_to r.name, band_path(r)%></td>
    	</tr>
	<%end%>
  </body>
</table>
<%end%>
<% if not @artist.records.empty? %>
<h3>Performer on <%= pluralize(@artist.records.count, 'record')%></h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
	<% @artist.records.each do |r| %>
    <tr>
	      <td><%= link_to r.name, record_path(r)%></td>
    </tr>
	<%end%>
  </body>
</table>
<%end%>

<br>

<p>
<% if current_user %>

<h3>Add a record or band</h3>
<%= form_tag(add_bands_artist_path, :method=>'put') do %>
 <p>
   <%= select_tag(:band_id, options_from_collection_for_select(@bands, :id, :name)) %>
   <%= submit_tag 'Add band' %> 
</p>
<%end%>
<%= form_tag(add_records_artist_path, :method=>'put') do %>
 <p>
   <%= select_tag(:record_id, options_from_collection_for_select(@records, :id, :name)) %>
   <%= submit_tag 'Add record' %> 
</p>
<%end%>  


<br>
<%= link_to edit_and_destroy_buttons(@artist), class:"btn btn-primary" %>
<% end %>
</p>