config/routes.rb
Recordz::Application.routes.draw do
  root 'records#index'

  resources :users
  resources :records
  resources :bands
  resources :artists
  resource :session, only: [:new, :create, :delete]
  resources :artists do
  	put 'add_bands', on: :member
	put 'add_records', on: :member
  end
  resources :bands do
	put 'add_artists', on: :member
	put 'add_records', on: :member
  end
  resources :records do
	put 'add_bands', on: :member
	put 'add_artists', on: :member
	put 'add_to_collection', on: :member
	put 'remove_from_collection', on: :member
  end

  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/models/record.rb
class Record < ActiveRecord::Base
	include AddRecords

	has_and_belongs_to_many :artists
	has_and_belongs_to_many :bands
	has_and_belongs_to_many :users

	validates :name, :year, presence: true
	validates :year, numericality: { greater_than_or_equal_to: 1860, only_integer: true }

	def add_collector(userid)
		if not self.users.find_by id:userid
		collector = User.find_by id:userid
		self.users << collector
		else return false
		end
	end

	def remove_collector(userid)
	if self.users.find_by id:userid
	self.users.delete(User.find userid)
	end
	end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy, :add_bands, :add_artists, :add_to_collection, :remove_from_collection]
  before_action :check_signed_in, except: [:index, :show]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
	@bands = Band.all
	@artists = Artist.all
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
   def add_artists
	artist = Artist.find(params[:artist_id])
	if @record.add_artist(artist)
	  redirect_to record_path(@record), notice: 'Artist was successfully added.'
	else 
	 redirect_to record_path(@record), notice: 'Failed to add artist. Already added?'
	end
  end

  def add_bands
	band = Band.find(params[:band_id])
	if @record.add_band(band)
	  redirect_to record_path(@record), notice: 'Band was successfully added.'
	else 
	 redirect_to record_path(@record), notice: 'Failed to add band. Already added?'
	end
  end
  def add_to_collection
	user = current_user.id
	if @record.add_collector(user)
	  redirect_to user_path(user), notice: 'Record added to collection.'
	else 
	 redirect_to user_path(user), notice: 'Already in collection?'
	end
  end
  def remove_from_collection
	user = current_user.id
	if @record.remove_collector(user)
	  redirect_to user_path(user), notice: 'Record removed from collection'
	else 
	 redirect_to user_path(user), notice: 'Record not in your collection?'
	end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:name, :info, :year, :performer_id)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :year_released %><br>
    <%= f.number_field :year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

app/views/records/index.html.erb
<h2>Records</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Performed by:</th>
      <th>Band</th>
      <th>Artist</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%=link_to record.name, record  %></td>
        <td><%= record.year %></td>
	<td></td>
        <td><% record.bands.each do |b|%><%=link_to b.name, band_path(b)%>, <%end%></td>
	<td><% record.artists.each do |a|%><%=link_to a.name, artist_path(a)%>, <%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p><%if current_user %>
<%= link_to 'New Record', new_record_path , class:"btn btn-primary" %>
<%end%>
</p>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<h1>
  <%= @record.name %>
</h1>

<p>
  <strong>Released in <%= @record.year %></strong>
</p>

<p>
  <%= @record.info %>
</p>
<p>In collection of <%= pluralize(@record.users.count, 'member')%>
<h3>Performed by</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Bands</th>
	<th>Artists</th>
    </tr>
  </thead>
  <tbody>
    	<tr>
        <td><% @record.bands.each do |b|%><%=link_to b.name, band_path(b)%>, <%end%></td>
	<td><% @record.artists.each do |a|%><%=link_to a.name, artist_path(a)%>, <%end%></td>
    	</tr>
  </body>
</table>
<p>
<br>
<% if current_user %>
<% if not current_user.records.find_by id:@record.id%>
	<%=link_to 'Add record to collection', add_to_collection_record_path, :method=>'put', class:"btn btn-primary" %>
<%else%> <%=link_to 'Remove from collection', remove_from_collection_record_path, :method=>'put', class:"btn btn-danger" %>
<%end%>
<br><br>
<h3>Add performer:</h3>
<%= form_tag(add_artists_record_path, :method=>'put') do %>
 <p>
   <%= select_tag(:artist_id, options_from_collection_for_select(@artists, :id, :name)) %>
   <%= submit_tag 'Add artist' %> 
</p>
<%end%>
<%= form_tag(add_bands_record_path, :method=>'put') do %>
 <p>
   <%= select_tag(:band_id, options_from_collection_for_select(@bands, :id, :name)) %>
   <%= submit_tag 'Add band' %> 
</p>
<%end%>  
</p>

<br>
<%= link_to edit_and_destroy_buttons(@record), class:"btn btn-primary" %>
<%end%>