config/routes.rb
Recordz::Application.routes.draw do
  root 'records#index'

  resources :users
  resources :records
  resources :bands
  resources :artists
  resource :session, only: [:new, :create, :delete]
  resources :artists do
  	put 'add_bands', on: :member
	put 'add_records', on: :member
  end
  resources :bands do
	put 'add_artists', on: :member
	put 'add_records', on: :member
  end
  resources :records do
	put 'add_bands', on: :member
	put 'add_artists', on: :member
	put 'add_to_collection', on: :member
	put 'remove_from_collection', on: :member
  end

  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/models/band.rb
class Band < ActiveRecord::Base
	include AddRecords

	has_and_belongs_to_many :artists
	has_and_belongs_to_many :records

	validates :name, :formed,  presence: true


	
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy, :add_records, :add_artists]
  before_action :check_signed_in, except: [:index, :show]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
	@artists = Artist.all
	@records = Record.all
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render action: 'show', status: :created, location: @band }
      else
        format.html { render action: 'new' }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url }
      format.json { head :no_content }
    end
  end

  def add_records
	rec = Record.find(params[:record_id])
	if @band.add_record(rec)
	  redirect_to band_path(@band), notice: 'Record was successfully added.'
	else 
	 redirect_to band_path(@band), notice: 'Failed to add record. Already added?'
	end
  end

  def add_artists
	artist = Artist.find(params[:artist_id])
	if @band.add_artist(artist)
	  redirect_to band_path(@band), notice: 'Artist was successfully added.'
	else 
	 redirect_to band_path(@band), notice: 'Failed to add artist. Already added?'
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :info, :formed, :status)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :formed %><br>
    <%= f.number_field :formed %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Listing bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>Formed</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= band.info %></td>
        <td><%= band.formed %></td>
        <td><%= band.status %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<h1>
  <%= @band.name %>
</h1>

<p>
  <%= @band.info %>
</p>

<p>
  <strong>Formed:</strong>
  <%= @band.formed %>
</p>

<p>
  <strong>Status:</strong>
  <%= @band.status %>
</p>

<% if not @band.artists.empty? %>
<h3><%= pluralize(@band.artists.count, 'Member')%></h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
	<% @band.artists.each do |r| %>
    	<tr>
	      <td><%= link_to r.name, r%></td>
    	</tr>
	<%end%>
  </body>
</table>
<%end%>
<% if not @band.records.empty? %>
<h3><%= pluralize(@band.records.count, 'Record')%></h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
	<% @band.records.each do |r| %>
    	<tr>
	      <td><%= link_to r.name, r%></td>
    	</tr>
	<%end%>
  </body>
</table>
<%end%>

<p>
<% if current_user %>

<h3>Add an artist or record</h3>
<%= form_tag(add_artists_band_path, :method=>'put') do %>
 <p>
   <%= select_tag(:artist_id, options_from_collection_for_select(@artists, :id, :name)) %>
   <%= submit_tag 'Add member' %> 
</p>
<%end%>
<%= form_tag(add_records_band_path, :method=>'put') do %>
 <p>
   <%= select_tag(:record_id, options_from_collection_for_select(@records, :id, :name)) %>
   <%= submit_tag 'Add record' %> 
</p>
<%end%>  
</p>

<br>
<%= link_to edit_and_destroy_buttons(@band), class:"btn btn-primary" %>
<%end%>