config/routes.rb
Recordz::Application.routes.draw do
  root 'records#index'

  resources :users
  resources :records
  resources :bands
  resources :artists
  resource :session, only: [:new, :create, :delete]
  resources :artists do
  	put 'add_bands', on: :member
	put 'add_records', on: :member
  end
  resources :bands do
	put 'add_artists', on: :member
	put 'add_records', on: :member
  end
  resources :records do
	put 'add_bands', on: :member
	put 'add_artists', on: :member
	put 'add_to_collection', on: :member
	put 'remove_from_collection', on: :member
  end

  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Records', records_path %></li>
<li><%= link_to 'Bands', bands_path %></li>
<li><%= link_to 'Artists', artists_path %></li>
<li><%= link_to 'Collectors', users_path %></li>
<% if not current_user.nil? %>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
      <%= current_user.username %> <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'My collection', current_user %></li>
    <li><%= link_to 'signout', signout_path, method: :delete %></li>
  </li>
<% else %>
    <li><%= link_to 'signin', signin_path %></li>
    <li><%= link_to 'signup', signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Recordz" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Recordz" %>">
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
   <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main" class=".container">
      <%= render 'layouts/messages' %>

      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
      </div>

    </main>
  </body>
</html>